// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Rime api
class RimeBridge {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RimeBridge(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RimeBridge.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  int init() {
    return _init();
  }

  late final _initPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function()>>('init');
  late final _init = _initPtr.asFunction<int Function()>();

  int start(
    ffi.Pointer<ffi.Int8> dir,
  ) {
    return _start(
      dir,
    );
  }

  late final _startPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Int8>)>>(
          'start');
  late final _start =
      _startPtr.asFunction<int Function(ffi.Pointer<ffi.Int8>)>();

  int process_key_name(
    ffi.Pointer<ffi.Int8> name,
  ) {
    return _process_key_name(
      name,
    );
  }

  late final _process_key_namePtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Int8>)>>(
          'process_key_name');
  late final _process_key_name =
      _process_key_namePtr.asFunction<int Function(ffi.Pointer<ffi.Int8>)>();

  int process_key(
    int code,
    int mask,
  ) {
    return _process_key(
      code,
      mask,
    );
  }

  late final _process_keyPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Int32, ffi.Int32)>>(
          'process_key');
  late final _process_key =
      _process_keyPtr.asFunction<int Function(int, int)>();

  ffi.Pointer<ffi.Int8> get_commit() {
    return _get_commit();
  }

  late final _get_commitPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int8> Function()>>(
          'get_commit');
  late final _get_commit =
      _get_commitPtr.asFunction<ffi.Pointer<ffi.Int8> Function()>();

  int finalize() {
    return _finalize();
  }

  late final _finalizePtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function()>>('finalize');
  late final _finalize = _finalizePtr.asFunction<int Function()>();
}
