name: flime
description: An android IME.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_rust_bridge: ^1.28.1
  auto_route: ^3.2.4
  flutter_mobx: ^2.0.5
  mobx: ^2.0.7
  provider: ^6.0.2
  synchronized: ^3.0.0+2
  fluent_ui: ^3.11.1
  path_provider: ^2.0.10
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
  auto_route_generator: ^3.2.3
  mobx_codegen: ^2.0.5+2
  pigeon: ^3.0.3
  ffigen: ^4.1.3

flutter:

  uses-material-design: true

  assets:
    - assets/rime/
    - assets/rime/opencc/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

ffigen:
  name: RimeBridge
  description: Rime api
  output: ./lib/api/rime_bridge.g.dart
  headers:
    entry-points:
      - native/include/api.h
