name: flime
description: First love is my everything.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: ^4.0.1
  dynamic_color: ^1.2.2
  ffi: ^1.2.1
  flutter: { sdk: flutter }
  flutter_mobx: ^2.0.5
  flutter_rust_bridge: ^1.33.0
  mobx: ^2.0.7+2
  nested: ^1.0.0
  path: ^1.8.1
  path_provider: ^2.0.10
  path_provider_android: ^2.0.14
  provider: ^6.0.3
  synchronized: ^3.0.0+2

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  ffigen: ^6.0.0
  flutter_lints: ^2.0.1
  flutter_test: { sdk: flutter }
  mobx_codegen: ^2.0.7
  pigeon: ^3.1.3

dependency_overrides:
  analyzer: ^3.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/rime/
    - assets/rime/opencc/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

ffigen:
  name: RimeBridge
  description: Rime api
  output: ./lib/api/rime_bridge.g.dart
  headers:
    entry-points:
      - native/include/api.h
