name: flime
description: An android IME.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_rust_bridge: ^1.28.1
  auto_route: ^4.0.1
  flutter_mobx: ^2.0.5
  mobx: ^2.0.7+2
  provider: ^6.0.2
  synchronized: ^3.0.0+2
  fluent_ui: ^3.12.0
  path_provider: ^2.0.10
  path: ^1.8.0
  nested: ^1.0.0
  path_provider_android: ^2.0.14
  ffi: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.1.10
  auto_route_generator: ^4.0.0
  mobx_codegen: ^2.0.5+2
  pigeon: ^3.0.3
  ffigen: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/rime/
    - assets/rime/opencc/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

ffigen:
  name: RimeBridge
  description: Rime api
  output: ./lib/api/rime_bridge.g.dart
  headers:
    entry-points:
      - native/include/api.h
