set(Boot_FOUND TRUE)
set(Boost_LIBRARIES Boost::filesystem Boost::regex Boost::system)
if(DEFINED ENV{BOOST_FOR_ANDROID_DIR} AND DEFINED ENV{BOOST_PREBUILD_VERSION})
  set(Boost_INCLUDE_DIRS "$ENV{BOOST_FOR_ANDROID_DIR}/build/out/${ANDROID_ABI}/include/boost-$ENV{BOOST_PREBUILD_VERSION}")
else()
  message("HOME DIR: $ENV{HOME}")
  message("Boost directory: $ENV{BOOST_FOR_ANDROID_DIR}")
  message("Boost version: $ENV{BOOST_PREBUILD_VERSION}")
  message(FATAL_ERROR "set BOOST_FOR_ANDROID_DIR and BOOST_PREBUILD_VERSION environment in .env")
endif()
